################################################################################
# R PACKAGE:   dimmeta
# FILE:        R/build.R
# DESCRIPTION: Utility script & instructions to build the R package
#              for submission to CRAN
# AUTHOR:      Enrique Bengoechea <enrique.bengoechea@credit-suisse.com>
# CREATED ON:  10/06/2009
# LICENSE:     GPL-2
################################################################################

# 0) Check all unit tests pass on a fresh install:
library(DevTools);
devPath(file.path("C:", "ebe", "Work", "Projects", "PaRiS_R", "dimmeta"));
ut()

# 1) Clear documentation produced in previous runs 
unlink(file.path(devPath(), "man", "*"))
unlink(file.path(devPath(), "chm", "*"))

# 2) Run Roxygen on the project (normally through StatET):
roxygen()

# 3) Remove Rd files generated by Roxygen that are not desired (doc files 
#    of objects that are documented together with other objects):

toRm <- c(
	"is.darray", 
	"as.darray", "as.darray.default", "as.darray.darray",
	"as.array.darray",
	"print.darray", 
	"dimmeta.default", "dimmetaReplace", "dimmetaReplace.default", 
 	"rowmeta", "rowmeta.default", "rowmetaReplace", "rowmetaReplace.default",
 	"colmeta", "colmeta.default", "colmetaReplace", "colmetaReplace.default",
	"unmeta", "unmeta.default",
	"cbind.darray",
	"dimReplace.darray",
	"indexLenSelection",
	"metalength.default",
	"metasubset.default",
	"metanamesReplace.default",	
	"metabind.default", "metabind.list", "metabind.matrix", 
		"metabind.data.frame",
	"as.dframe", "as.dframe.default", "as.dframe.dframe"
);
 
unlink(file.path(devPath(), "man", paste(toRm, ".Rd", sep="")))

# 4) Check the package (normally through StatET)
# R CMD Check
