################################################################################
# R PACKAGE:   metadata
# FILE:        R/build.R
# DESCRIPTION: Utility script & instructions to build the R package
#              for submission to CRAN
# AUTHOR:      Enrique Bengoechea <enrique.bengoechea@credit-suisse.com>
# CREATED ON:  10/06/2009
# LICENSE:     GPL-2
################################################################################

# 0) Check all unit tests pass on a fresh install:
library(DevTools);
devPath(file.path("C:", "ebe", "Work", "Projects", "PaRiS_R", "metadata"));
ut()

# 1) Clear documentation produced in previous runs 
unlink(file.path(devPath(), "man", "*"))
unlink(file.path(devPath(), "chm", "*"))

# 2) Run Roxygen on the project (normally through StatET):
roxygen()

# 3) Remove Rd files generated by Roxygen that are not desired (doc files 
#    of objects that are documented together with other objects):

toRm <- c(
	"is.marray", 
	"as.marray", "as.marray.default", "as.marray.marray",
	"as.array.marray",
	"print.marray", 
	"dimdata.default", "dimdataReplace", "dimdataReplace.default", 
 	"rowdata", "rowdata.default", "rowdataReplace", "rowdataReplace.default",
 	"coldata", "coldata.default", "coldataReplace", "coldataReplace.default",
	"cbind.marray"
);
 
unlink(file.path(devPath(), "man", paste(toRm, ".Rd", sep="")))

# 4) Check the package (normally through StatET)
# R CMD Check
